# No newline at start
add_newline = false

format = """
$cmd_duration 󰜥 $directory $python $git_branch
$character"""

# --------------------------
# CHARACTER (PROMPT SYMBOL)
# --------------------------
[character]
success_symbol = "[   ](bold fg:#7974f1)"
error_symbol   = "[   ](bold fg:#4944b4)"

# --------------------------
# GIT BRANCH
# --------------------------
[git_branch]
symbol = "󰘬"
style = "bg:#4944b4 fg:#f7f7f8"
truncation_length = 12
format = "󰜥 [](bold fg:#4944b4)[$symbol $branch]($style)[ ](bold fg:#4944b4)"

# --------------------------
# DIRECTORY
# --------------------------
[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#1e1c4a fg:#f7f7f8"
format = '[](bold fg:#1e1c4a)[󰉋 $path]($style)[](bold fg:#1e1c4a)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

# --------------------------
# CMD DURATION
# --------------------------
[cmd_duration]
min_time = 0
style = "bg:#7974f1 fg:#f7f7f8"
format = '[](bold fg:#7974f1)[󰪢 $duration]($style)[](bold fg:#7974f1)'

# --------------------------
# HOSTNAME
# --------------------------
[hostname]
style = "bg:#363385 fg:#f7f7f8"
format = "[](bold fg:#363385)[•$hostname]($style)[](bold fg:#363385)"
ssh_only = false
disabled = false

# --------------------------
# USERNAME
# --------------------------
[username]
style_user = "bold bg:#1a1840 fg:#f7f7f8"
format = "[](bold fg:#1a1840)[$user]($style)[](bold fg:#1a1840)"
show_always = true

# --------------------------
# PACKAGE
# --------------------------
[package]
disabled = true

# --------------------------
# PYTHON VENV
# --------------------------
[python]
disabled = false
detect_extensions = []
detect_files = []
detect_folders = []
symbol = ""
style = "bg:#0f09a5 fg:#e4e4e7"
format = '[](bold fg:#0f09a5)[$symbol ($virtualenv)]($style)[](bold fg:#0f09a5)'
