# No newline at start
add_newline = false

format = """
$cmd_duration 󰜥 $directory $python $git_branch
$character"""

# --------------------------
# CHARACTER (PROMPT SYMBOL)
# --------------------------
[character]
success_symbol = "[   ](bold fg:#74b1f1)"
error_symbol   = "[   ](bold fg:#4378b1)"

# --------------------------
# GIT BRANCH
# --------------------------
[git_branch]
symbol = "󰘬"
style = "bg:#4378b1 fg:#f7f7f8"
truncation_length = 12
format = "󰜥 [](bold fg:#4378b1)[$symbol $branch]($style)[ ](bold fg:#4378b1)"

# --------------------------
# DIRECTORY
# --------------------------
[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#1b3047 fg:#f7f7f8"
format = '[](bold fg:#1b3047)[󰉋 $path]($style)[](bold fg:#1b3047)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

# --------------------------
# CMD DURATION
# --------------------------
[cmd_duration]
min_time = 0
style = "bg:#74b1f1 fg:#f7f7f8"
format = '[](bold fg:#74b1f1)[󰪢 $duration]($style)[](bold fg:#74b1f1)'

# --------------------------
# HOSTNAME
# --------------------------
[hostname]
style = "bg:#315982 fg:#f7f7f8"
format = "[](bold fg:#315982)[•$hostname]($style)[](bold fg:#315982)"
ssh_only = false
disabled = false

# --------------------------
# USERNAME
# --------------------------
[username]
style_user = "bold bg:#172a3d fg:#f7f7f8"
format = "[](bold fg:#172a3d)[$user]($style)[](bold fg:#172a3d)"
show_always = true

# --------------------------
# PACKAGE
# --------------------------
[package]
disabled = true

# --------------------------
# PYTHON VENV
# --------------------------
[python]
disabled = false
detect_extensions = []
detect_files = []
detect_folders = []
symbol = ""
style = "bg:#0954a4 fg:#e4e5e7"
format = '[](bold fg:#0954a4)[$symbol ($virtualenv)]($style)[](bold fg:#0954a4)'
